---
title: "Education"
author: "Sedrek Kovar"
date: '2021-03-10'
slug: education
tags:
- resume
- experience
- education
- about
categories:
- Resume
- Experience
- Education
- About
---

# Education

#### Graduate
I graduated from Virginia Commonwealth University in 2020 with my master's degree in Environmental Studies (MENVS), in which I completed both a professional internship as well as an independent study. For the independent study, I advised the Virginia Department of Environmental Quality on best practices for automated watershed delineation methods. For my internship, I worked with the Virginia Department of Game and Inland Fisheries in their freshwater mussell propogation program. 

#### Undergraduate
I graduated from VCU with my B.S. in Environmental Studies in 2018, with a minor in Electrical Engineering. In 2014 I started off at Virginia Polytechnic Institute studying physics, but transferred to VCU to study computer engineering my sophmore year. Despite loving computers and programming, I realized that I was passionate about doing environmental work, and decided to change majors once again during my junior year. Initially I was concerned the switch was too late, but it turns out that my programming and technical skills would be of great use to the field! After having programmed mostly in C/C++, it was a joy to learn about the rich world of environmental data.
